### ISSUE TITLE
-

### ISSUE THREAD

**Issue by zavyazin** [nanoboard/nanoboard#1]
Аргументы командной строки запили мне. И гайд для дебилов.

**Comment by nanoboard** [comment]
аргументов командной строки нет, гайд есть в ридми
если нужно настроить IP/port то это сейчас делается путем правки файликов ip.txt и port.txt

**Comment by asxcandrew** [comment]
Почему на сисярпе, почему не java/python/ruby?

**Comment by nanoboard** [comment]
Может этого оттого, что я плохо знаю Java, но мне кажется, что Java в сравнении с C# - откровенно слабый язык. Я там, конечно, все то же самое смогу сделать но с гораздо большей болью/объемом кода. И не понимаю ради чего - Java принадлежит Ораклу, Mono - сообществу. Почему Моно ставить зашкварно а JRE нет? Потому что к .NET приложил руку Мелкософт? Это все выебоны и срач на пустом месте. Справедливости ради упомяну что JVM в бенчмарках немного быстрее Моно (в среднем в 2 раза) (.NET в этом плане пошустрее).
Python/Ruby - слишком медленные, у питона подводные камни типа GIL, в общем надо обмазываться всякими левыми библиотечками (да и с Ruby тоже). В C# у меня всё изкаробки.

**Comment by nanoboard** [comment]
Closed as not an issue.
